services:
  db:
    image: postgres:16-alpine
    container_name: pg-sales
    environment:
      POSTGRES_DB: DeveloperEvaluation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"                # 👈 muda a porta do HOST para 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]   # 👈 sem fixar o DB
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  api:
    container_name: sales-api
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=DeveloperEvaluation;Username=postgres;Password=postgres"
      Jwt__Issuer: "Ambev.DeveloperEvaluation"
      Jwt__Audience: "Ambev.DeveloperEvaluation"
      Jwt__Key: "super-secret-mas-bem-grande-para-HMAC"
      Jwt__ExpiresMinutes: "60"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
